// English. It is also the label set any language without its own file falls back to.
export default {
  id: 'en',
  language: 'en',
  voice: { say: 'en_US', espeak: 'en-us' },
  ui: {
    remark: {
      button: 'Remark',
      hint: 'Optional note', save: 'Save', remove: 'Remove',
      section: 'Remarks',
      kinds: { suggestion: 'suggestion', keep: 'keep', question: 'question', concern: 'concern' },
    },
    theme: 'Theme', modeLabel: 'Mode',
    mode: { auto: 'Auto', light: 'Light', dark: 'Dark' },
    copy: 'Copy source', done: 'Copied ✓', copyCode: 'Copy',
    reply: {
      button: 'Reply', comment: 'Comment', commentHint: 'Your comment on this panel', title: 'Your reply',
      hint: 'Copy it and paste it into the chat.', copy: 'Copy reply', close: 'Close', suggested: 'suggested',
      empty: 'Pick options, or comment on a panel first.', decisions: 'Decisions', comments: 'Comments',
      confirmed: 'suggestion confirmed', untouched: 'not answered; suggestion kept', was: 'was',
      typed: 'Lines that start with ">" are text the reader typed.',
    },
    toc: 'Contents', flow: 'Flowchart', sequence: 'Sequence diagram', er: 'Entity relationship diagram', colon: ': ', sep: ', ',
    expand: 'Expand diagram', close: 'Close', diagram: 'Diagram viewer',
    delta: { added: 'added', removed: 'removed', changed: 'changed', view: 'View', before: 'Before', changes: 'Changes', after: 'After' },
    generated: 'Generated by', limits: { value: '{value} / max {limit}', limit: 'max {limit}' },
  },
  // Player labels. drawn..duration are the title block cells; sheet is the scene header, with {n} and {total} the zero-padded numbers.
  videoUi: {
    play: 'Play', pause: 'Pause', chapters: 'Chapters', speed: 'Speed', export: 'Export',
    drawn: 'DRAWN', date: 'DATE', scenes: 'SCENES', duration: 'DURATION', sheet: 'SHEET {n} / {total}',
  },
};
