// Japanese.
// `langs` are the :lang() ranges the fonts apply to (a range matches the tag and every tag that starts with it, so `ja` covers `ja-JP`).
// Japanese fonts come before Chinese ones: a named Chinese font overrides the language, and Han characters would use Chinese glyphs (`直`, `込`).
// `serif` is the CJK part of a theme's serif stack; the theme puts its own Latin fonts in front.
export default {
  id: 'ja',
  language: 'ja',
  voice: { say: 'ja_JP', espeak: 'ja' },
  langs: ['ja'],
  fonts: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", "Hiragino Kaku Gothic ProN", "Yu Gothic UI", "Yu Gothic", Meiryo, "Noto Sans CJK JP", "Noto Sans JP", "PingFang SC", "Microsoft YaHei", Roboto, "Helvetica Neue", Arial, sans-serif',
    serif: '"Hiragino Mincho ProN", "Yu Mincho", "Noto Serif CJK JP", "Noto Serif JP", "Songti SC"',
  },
  ui: {
    remark: {
      button: '注記',
      hint: 'メモ（任意）', save: '保存', remove: '削除',
      section: '注記',
      kinds: { suggestion: '提案', keep: '維持', question: '質問', concern: '懸念' },
    },
    theme: 'テーマ', modeLabel: '表示',
    mode: { auto: '自動', light: 'ライト', dark: 'ダーク' },
    copy: '原稿をコピー', done: 'コピーしました ✓', copyCode: 'コピー',
    reply: {
      button: '返信', comment: 'コメント', commentHint: 'このパネルへのコメント', title: 'あなたの返信',
      hint: 'コピーしてチャットに貼り付けてください。', copy: '返信をコピー', close: '閉じる', suggested: '推奨',
      empty: '選択肢を選ぶか、パネルにコメントしてください。', decisions: '決定', comments: 'コメント',
      confirmed: '推奨を確認', untouched: '未回答（推奨のまま）', was: '変更前',
      typed: '「>」で始まる行は読者が入力した文字です。',
    },
    toc: '目次', flow: 'フローチャート', sequence: 'シーケンス図', er: 'ER 図', colon: '：', sep: '、',
    expand: '拡大表示', close: '閉じる', diagram: 'ダイアグラム',
    delta: { added: '追加', removed: '削除', changed: '変更', view: '表示', before: '変更前', changes: '差分', after: '変更後' },
    generated: 'Generated by', limits: { value: '{value} / max {limit}', limit: 'max {limit}' },
  },
  videoUi: {
    play: '再生', pause: '一時停止', chapters: '章', speed: '速度', export: '書き出し',
    drawn: '作図', date: '日付', scenes: 'シーン', duration: '再生時間', sheet: 'シート {n} / {total}',
  },
};
