// Traditional Chinese. It covers the Hant script and the regions that write it (Taiwan, Hong Kong, Macao), and never borrows the Simplified labels.
// Traditional fonts come before Simplified ones, so systems whose default Chinese font is Simplified still draw Traditional glyphs.
export default {
  id: 'zh-Hant',
  language: 'zh',
  script: 'Hant',
  voice: { say: 'zh_TW', espeak: 'cmn' },
  langs: ['zh-Hant', 'zh-TW', 'zh-HK', 'zh-MO'],
  fonts: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang TC", "Heiti TC", "Microsoft JhengHei", "Noto Sans CJK TC", "Noto Sans TC", "PingFang SC", "Microsoft YaHei", Roboto, "Helvetica Neue", Arial, sans-serif',
    serif: '"Songti TC", "PMingLiU", "MingLiU", "Noto Serif CJK TC", "Noto Serif TC", "Source Han Serif TC", "Songti SC"',
  },
  ui: {
    remark: {
      button: '標註',
      hint: '批註（可選）', save: '儲存', remove: '刪除',
      section: '標註',
      kinds: { suggestion: '建議', keep: '保留', question: '疑問', concern: '關注' },
    },
    theme: '主題', modeLabel: '明暗',
    mode: { auto: '跟隨系統', light: '淺色', dark: '深色' },
    copy: '複製源稿', done: '已複製 ✓', copyCode: '複製',
    reply: {
      button: '回覆', comment: '評論', commentHint: '對這個面板的意見', title: '你的回覆',
      hint: '複製後貼到對話裡。', copy: '複製回覆', close: '關閉', suggested: '建議',
      empty: '先選擇選項，或在面板上寫評論。', decisions: '決定', comments: '評論',
      confirmed: '確認了建議', untouched: '未作答，保留建議', was: '原為',
      typed: '以 ">" 開頭的行是讀者輸入的文字。',
    },
    toc: '目錄', flow: '流程圖', sequence: '時序圖', er: '實體關聯圖', colon: '：', sep: '、',
    expand: '展開查看圖表', close: '關閉', diagram: '圖表檢視',
    delta: { added: '新增', removed: '刪除', changed: '修改', view: '檢視', before: '改前', changes: '變更', after: '改後' },
    generated: 'Generated by', limits: { value: '{value} / max {limit}', limit: 'max {limit}' },
  },
  videoUi: {
    play: '播放', pause: '暫停', chapters: '章節', speed: '速度', export: '匯出',
    drawn: '製圖', date: '日期', scenes: '場景', duration: '時長', sheet: '圖 {n} / {total}',
  },
};
