// 把 CLI 打包成单文件 <skill>/scripts/am.mjs（本目录 dev/ 的上一级就是 skill 根目录）。
// 产物随 skill 目录分发：用 npx skills add / 插件市场安装后无需 npm install，有 Node 即可运行。
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');

// 用内联字符串替换 src/assets.js，去掉运行时对磁盘文件的依赖。
const inlineAssets = {
  name: 'inline-assets',
  setup(b) {
    b.onLoad({ filter: /src[\\/]assets\.js$/ }, () => ({
      loader: 'js',
      contents: [
        `export const VERSION = ${JSON.stringify(JSON.parse(read('../package.json')).version)};`,
        `export const BASE_CSS = ${JSON.stringify(read('../src/themes/base.css'))};`,
        `export const RUNTIME_JS = ${JSON.stringify(read('../src/runtime/page.js'))};`,
        `export const DIAGRAM_JS = ${JSON.stringify(read('../src/runtime/diagrams.js'))};`,
      ].join('\n'),
    }));
  },
};

await build({
  entryPoints: [fileURLToPath(new URL('../bin/am.js', import.meta.url))],
  outfile: fileURLToPath(new URL('../../scripts/am.mjs', import.meta.url)),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'eof',
  banner: { js: '// answer-me-with-html CLI (research fork) — generated by dev/scripts/build.mjs, do not edit. Source: ../dev/src; upstream: https://github.com/QingYunA/answer-me-with-html' },
  plugins: [inlineAssets],
  logLevel: 'info',
});
