// Bundle the CLI into the single file <skill>/scripts/am.mjs (the parent of this dev/ directory is the skill root).
// The bundle ships with the skill directory and runs with Node alone, no npm install.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { inlineAssets } from './inline-assets.mjs';

await build({
  entryPoints: [fileURLToPath(new URL('../bin/am.js', import.meta.url))],
  outfile: fileURLToPath(new URL('../../scripts/am.mjs', import.meta.url)),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'eof',
  banner: { js: '// answer-me-with-html CLI (research fork) — generated by dev/scripts/build.mjs, do not edit. Source: ../dev/src; upstream: https://github.com/QingYunA/answer-me-with-html' },
  plugins: [inlineAssets],
  logLevel: 'info',
});
